### ISSUE TITLE
React warning about render time state changes

### ISSUE THREAD

**Issue by theronburger** [fluent-ai/fluent-ai#167]
react-dom.development.js:86 Warning: Cannot update a component (`LoadDialog`) while rendering a different component (`RemoteRunnerDialog`). To locate the bad setState() call inside `RemoteRunnerDialog`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
    at RemoteRunnerDialog (http://localhost:4200/main.js:8715:3)
    at div
    at div
    at div
    at NodeDialogComponent (http://localhost:4200/main.js:5460:76)
    at ReactFlowProvider (http://localhost:4200/vendor.js:18812:30)
    at div
    at Dashboard (http://localhost:4200/main.js:932:76)
    at App (http://localhost:4200/main.js:39:76)
    at Router (http://localhost:4200/vendor.js:158767:15)
    at BrowserRouter (http://localhost:4200/vendor.js:159364:5)
    at Provider (http://localhost:4200/vendor.js:151481:3)
    at StateProvider (http://localhost:4200/main.js:3070:3)

**Comment by theronburger** [comment]
Actually quite a big thing to fix. 

When a node is created, it has no defaults. The defaults are populated by the node dialog...
When the dialog is opened, if items are undefined, it triggers a pile of dispatches.

```typescript
function JsonDialog({ nodeId }: { nodeId: string }) {
  const dispatch = useDispatch();
  const inputs = useSelector(flowSelectors.getInputsById(nodeId));
  const outputs = useSelector(flowRunnerSelectors.selectOutput(nodeId));

  ...

  if (inputs?.inputPath === undefined) {
    dispatch(
      flowActions.setInput({
        id: nodeId,
        nodeInputs: { ...inputs, inputPath: 'msg.payload' },
      })
    );
  }
  if (inputs?.outputPath === undefined) {
    dispatch(
      flowActions.setInput({
        id: nodeId,
        nodeInputs: { ...inputs, outputPath: 'msg.payload' },
      })
    );
  }

```

Ideally there would be a node creation phase, perhaps after the reactFlow onDrop event
